=== tucq88/os_thoibaonh/doc/dtd/layout.dtd
<!--
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version		$Id: layout.dtd 916 2010-01-21 06:45:33Z huuphuoc $
 */
-->

<!--
This is DTD for layout configuration file.
Put the following line at the top of layout file:
<!DOCTYPE layout SYSTEM "http://schemas.tomatocms.com/dtd/layout.dtd">
-->

<!-- ========== Root element =============================================== -->
<!--
Layout contain one or many container(s) 
-->
<!ELEMENT layout (container)+>

<!-- ========== Container ================================================== -->
<!-- Each container can contain zero or many containers/widgets -->
<!ENTITY % Block "(container | widget | defaultOutput)*">
<!ELEMENT container (%Block;)>

<!-- Container attributes:
- cols (optional): Define the number of columns. This attribute is required in most cases.
If you build template which support mobile devices, you don't have to define this value
- position: Position of container in the row it belong to.
Here, row is the parent container with full of 12 columns.
The position can take one of two values: 
"first" if the container is the first container in row, or
"last" if the container is the last one in row.
This attribute is optional
- cssClass (optional): CSS class of container
-->
<!ATTLIST container
	cols CDATA #IMPLIED
  	position (first|last) #IMPLIED
  	cssClass CDATA #IMPLIED>
  
<!-- ========== Widget ===================================================== -->

<!-- Default output. 
This is all what user will see on web page without widgets
-->
<!ELEMENT defaultOutput EMPTY>

<!-- Each widget may need some resources -->
<!ELEMENT widget (title*,resources*, params*,cache*)>

<!-- Widget attributes:
- module (required): Name of module that widget belong to
- name (required): Name of widget
- load (optional): The loading method. Each widget can be loaded by php (default) or ajax
- cssClass (optional): CSS class of widget
-->
<!ATTLIST widget 
  	module CDATA #REQUIRED
  	name CDATA #REQUIRED
  	load (php|ajax) #IMPLIED
  	cssClass CDATA #IMPLIED>

<!ELEMENT title (#PCDATA)>
<!ELEMENT resources (resource*)>
<!ELEMENT resource (#PCDATA)>

<!-- Resource attributes:
- type (required): The resource type. Take value javascript (or css)
- src (required): The source of resource.
Its value can contain pre-defined string {APP_URL} or {APP_STATIC_SERVER}.
{APP_URL} will be replaced with URL of website
{APP_STATIC_SERVER} is URL to static server, which contain static resources as javascript or css files
-->
<!ATTLIST resource
  	type (javascript|css) #REQUIRED
  	src CDATA #REQUIRED>

<!ELEMENT params (param*)>
<!ELEMENT param (value*)>

<!-- Param attributes:
- name (required): Name of param
- type (optional): If this param is used, it has to be "global" that means the value of param will be
determined from URL request automatically
- from (optional): This param is used if only if the type attribute is defined.
This param define the name of request param which the param will take value from
-->
<!ATTLIST param
  	name CDATA #REQUIRED
  	type (global) #IMPLIED
  	from CDATA #IMPLIED>

<!-- Value of param 
This is not required if the param value will be taken from request 
(the "type" attribute defined as "global") 
-->
<!ELEMENT value (#PCDATA)>

<!-- Cache element -->
<!ELEMENT cache (#PCDATA)>

<!-- Cache attributes:
- lifetime (required): Cache lifetime in seconds
-->
<!ATTLIST cache
  	lifetime CDATA #REQUIRED>

=== tucq88/os_thoibaonh/app/templates/tbnh/layouts/ban_doc.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE layout SYSTEM "http://schemas.tomatocms.com/dtd/layout.dtd"><layout><container cols="12"><container cols="6"><widget module="news" name="breadcump" load="php"><title><![CDATA[Breadcump]]></title><resources></resources><params><param name="category_id" type="global" /></params></widget><defaultOutput /></container><container cols="4"></container><container cols="2" position="last"></container></container></layout>

=== tucq88/os_thoibaonh/app/templates/tbnh/layouts/news_article_details.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE layout SYSTEM "http://schemas.tomatocms.com/dtd/layout.dtd"><layout><container cols="12"><widget module="news" name="category" load="php"><title><![CDATA[Category]]></title><resources></resources><params><param name="category_id" type="global" /></params></widget></container><container cols="12"><container cols="6" position="first"><widget module="news" name="breadcump" load="php"><title><![CDATA[Breadcump]]></title><resources></resources><params><param name="category_id" type="global" /></params></widget><widget module="utility" name="socialshare" load="php"><title><![CDATA[Share via social networks]]></title><resources></resources><params></params></widget><defaultOutput /><widget module="comment" name="comment" load="php"><title><![CDATA[Latest comments]]></title><resources></resources><params><param name="limit"><value><![CDATA[5]]></value></param><param name="allow_comment"><value><![CDATA[1]]></value></param><param name="show_avatar"><value><![CDATA[0]]></value></param><param name="avatar_size"><value><![CDATA[]]></value></param></params></widget><widget module="news" name="older" load="php"><title><![CDATA[Older articles]]></title><resources></resources><params><param name="article_id" type="global" /><param name="category_id"><value><![CDATA[1]]></value></param><param name="limit"><value><![CDATA[15]]></value></param></params></widget></container><container cols="4"><widget module="news" name="sticky" load="php"><title><![CDATA[Sticky articles]]></title><resources><resource type="javascript" src="http://thoibaonganhang.vn//js/jquery.cycle/jquery.cycle.all.min.js" /></resources><params><param name="category_id" type="global" /><param name="limit"><value><![CDATA[5]]></value></param><param name="num_articles_per_row"><value><![CDATA[5]]></value></param></params></widget><widget module="news" name="mostviewed" load="php"><title><![CDATA[Most viewed]]></title><resources><resource type="javascript" src="http://thoibaonganhang.vn//js/jquery.cycle/jquery.cycle.all.min.js" /></resources><params><param name="category_id" type="global" /><param name="limit"><value><![CDATA[5]]></value></param></params></widget><widget module="multimedia" name="slideshow" load="php"><title><![CDATA[Slideshow]]></title><resources><resource type="javascript" src="http://thoibaonganhang.vn//js/jquery.cycle/jquery.cycle.all.min.js" /></resources><params><param name="limit"><value><![CDATA[10]]></value></param></params></widget></container><container cols="2" position="last"></container></container></layout>
