=== tucq88/os_thoibaonh/doc/dtd/template_about.dtd
<!--
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version		$Id: template_about.dtd 916 2010-01-21 06:45:33Z huuphuoc $
 */
-->

<!-- Root element -->
<!ELEMENT template (name, description, thumbnail, author, email, version, license, selectable, skins, install)+>

<!-- Name of template -->
<!ELEMENT name (#PCDATA)>

<!-- Description of template -->
<!ELEMENT description (#PCDATA)>

<!-- The thumbnail URL -->
<!ELEMENT thumbnail (#PCDATA)>

<!-- Author -->
<!ELEMENT author (#PCDATA)>

<!-- Email to contact with author -->
<!ELEMENT email (#PCDATA)>

<!-- Template version -->
<!ELEMENT version (#PCDATA)>

<!-- Template license -->
<!ELEMENT license (#PCDATA)>

<!-- The template is selectable or not -->
<!ELEMENT selectable (#PCDATA)>

<!-- Skins of template -->
<!ELEMENT skins (skin)*>

<!-- Skin of template -->
<!ELEMENT skin (color, description)+>

<!ATTLIST skin
	name CDATA #REQUIRED>
<!ELEMENT color (#PCDATA)>	

<!ELEMENT install (query)*>

<!-- SQL query. Used when install or uninstall a template -->
<!ELEMENT query (#PCDATA)>

=== tucq88/os_thoibaonh/app/templates/tbnh/about.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template SYSTEM "http://schemas.tomatocms.com/dtd/template_about.dtd">
<template>
	<name>tbnh</name>
	<description>News Vnexpress.net template</description>
	<thumbnail></thumbnail>
	<author>UNNET</author>
	<email>kyo.kunvk@gmail.com</email>
	<version>2.0.4</version>
	<license>free</license>
	<selectable>true</selectable>
	<skins>
		<skin name="default">
			<color>#F1F1F1</color>
			<description>Default skin</description>
		</skin>
	</skins>
	<install>
	</install>
</template>
