=== tucq88/os_thoibaonh/doc/dtd/widget_about.dtd
<!--
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version		$Id: widget_about.dtd 916 2010-01-21 06:45:33Z huuphuoc $
 */
-->

<!-- Root element -->
<!ELEMENT widget (name, title, module, description, thumbnail, author, email, version, license, params, resources)+>

<!-- Name of widget. It is the name of folder contain all widget files. -->
<!ELEMENT name (#PCDATA)>

<!-- Title of widget -->
<!ELEMENT title (#PCDATA)>

<!-- Name of module that widget belong to -->
<!ELEMENT module (#PCDATA)>

<!-- Description of widget -->
<!ELEMENT description (#PCDATA)>

<!-- The thumbnail URL -->
<!ELEMENT thumbnail (#PCDATA)>

<!-- Author -->
<!ELEMENT author (#PCDATA)>

<!-- Email to contact with author -->
<!ELEMENT email (#PCDATA)>

<!-- Widget version -->
<!ELEMENT version (#PCDATA)>

<!-- Widget license -->
<!ELEMENT license (#PCDATA)>

<!-- Widget parameters -->
<!ELEMENT params (param)*>
<!ELEMENT param (description)>

<!-- Parameter attributes:
- name (required): Name of param
-->
<!ATTLIST param
	name CDATA #REQUIRED>

<!-- Resources -->
<!ELEMENT resources (resource)*>

<!ELEMENT resource EMPTY>

<!-- Resource attributes:
- type (required): Type of resource. Can take one of two value: javascript or css
- src (required): URL to resource. You can use pre-defined two constants in this attribute:
{APP_URL} - The website URL
and 
{APP_STATIC_SERVER} - The URL to static server
-->
<!ATTLIST resource
	type (javascript|css) #REQUIRED
	src CDATA #REQUIRED>

=== tucq88/os_thoibaonh/app/modules/utility/widgets/stock/about.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE widget SYSTEM "http://schemas.tomatocms.com/dtd/widget_about.dtd">
<widget>
	<name>Stock</name>
	<title>Stock table</title>
	<module>utility</module>
	<description>Show stock table from vnexpress.net</description>
	<thumbnail></thumbnail>
	<author>Ninh Gio`</author>
	<email>ninhgio@yahoo.com</email>
	<version>2.0.4</version>
	<license>free</license>
	<params>
	</params>
	<resources>
		<resource type="css" src="{APP_STATIC_SERVER}/js/jquery.ui/themes/base/ui.all.css" />
		<resource type="javascript" src="{APP_STATIC_SERVER}/js/jquery.ui/ui.core.js" />
		<resource type="javascript" src="{APP_STATIC_SERVER}/js/jquery.ui/ui.tabs.js" />
	</resources>
</widget>

=== tucq88/os_thoibaonh/app/modules/news/widgets/topic/about.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE widget SYSTEM "http://schemas.tomatocms.com/dtd/widget_about.dtd">
<widget>
	<name>Topic</name>
	<title>Topic articles</title>
	<module>news</module>
	<description>Show articles from keyword</description>
	<thumbnail></thumbnail>
	<author>Ninh Gio`</author>
	<email>ninhgio@yahoo.com</email>
	<version>2.0.5</version>
	<license>free</license>
	<params>
		<param name="tag_id">
			<description>Id of category</description>
		</param>
		<param name="limit">
			<description>Number of articles</description>
		</param>
	</params>
	<resources></resources>
</widget>

=== tucq88/os_thoibaonh/app/modules/news/widgets/detail/about.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE widget SYSTEM "http://schemas.tomatocms.com/dtd/widget_about.dtd">
<widget>
	<name>Detail</name>
	<title>Detail</title>
	<module>news</module>
	<description>Article detail</description>
	<thumbnail></thumbnail>
	<author>Ninh Gio`</author>
	<email>ninhgio@yahoo.com</email>
	<version>2.0.4</version>
	<license>free</license>
	<params>
		<param name="article_id">
			<description>Id of article</description>
		</param>
	</params>
	<resources></resources>
</widget>

=== tucq88/os_thoibaonh/app/modules/utility/widgets/weatherforex/about.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE widget SYSTEM "http://schemas.tomatocms.com/dtd/widget_about.dtd">
<widget>
	<name>Weatherforex</name>
	<title>Weather and forex</title>
	<module>utility</module>
	<description>Show weather and forex from vnexpress.net</description>
	<thumbnail></thumbnail>
	<author>Ninh Gio`</author>
	<email>ninhgio@yahoo.com</email>
	<version>2.0.5</version>
	<license>free</license>
	<params>
	</params>
	<resources>
		<resource type="css" src="{APP_STATIC_SERVER}/skin/zing/default/ultility.css" />
	</resources>
</widget>

=== tucq88/os_thoibaonh/app/modules/utility/widgets/zingtopsong/about.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE widget SYSTEM "http://schemas.tomatocms.com/dtd/widget_about.dtd">
<widget>
	<name>Zingtopsong</name>
	<title>Zing top song</title>
	<module>utility</module>
	<description>Show top song on mp3.zing.vn</description>
	<thumbnail></thumbnail>
	<author>Ninh Gio`</author>
	<email>ninhgio@yahoo.com</email>
	<version>2.0.5</version>
	<license>free</license>
	<params>
		<param name="url">
			<description>Zing top song URL</description>
		</param>
		<param name="limit">
			<description>Number of songs displayed</description>
		</param>
	</params>
	<resources>
		<resource type="css" src="{APP_STATIC_SERVER}/skin/zing/default/hotsong.css" />
	</resources>
</widget>

=== tucq88/os_thoibaonh/app/modules/utility/widgets/television/about.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE widget SYSTEM "http://schemas.tomatocms.com/dtd/widget_about.dtd">
<widget>
	<name>Television</name>
	<title>Lịch phát sóng truyền hình</title>
	<module>utility</module>
	<description>Lịch phát sóng truyền hình từ vnexpress.net</description>
	<thumbnail></thumbnail>
	<author>Ninh Gio`</author>
	<email>ninhgio@yahoo.com</email>
	<version>2.0.4</version>
	<license>free</license>
	<params>
	</params>
	<resources>
	</resources>
</widget>
